### ISSUE TITLE
Tags for sytest-synapse images should be renamed

### ISSUE THREAD

**Issue by callahad** [matrix-org/sytest#1003]
Currently, our `sytest-synapse` images are built with different Debian base images to yield images with an assortment of Python and PostgreSQL versions:

https://github.com/matrix-org/sytest/blob/6b1ae9efdd6d7128daeb31260755b2bdcc8a7348/docker/build.sh#L9-L11

This is misleading and error-prone, as `bullseye` is currently Debian's testing release, and thus subject to version upgrades.

For example, the image tagged `py38` and described as "Python 3.8 / Postgres 12 / Monolith" in the [Synapse pipeline](https://github.com/matrix-org/pipelines/blob/8cdf2a59660b83e5a0366928afec9387a5593b6c/synapse/pipeline.yml#L367) would currently build with Python 3.9 and PostgreSQL 13. See #1002

## Proposal

- Use Debian release names for the tags of stable Debian releases
- Use `testing` (and `unstable`, etc.) as the names of other releases

This would yield:

- `sytest-synapse:py35` → `sytest-synapse:stretch`
- `sytest-synapse:py37` → `sytest-synapse:buster`
- `sytest-synapse:py38` → `sytest-synapse:testing`

**Comment by richvdh** [comment]
right, but how would we set up the synapse pipeline to ensure that we are covering the desired ranges of python and postgres?

**Comment by callahad** [comment]
The `trial` and `port_db` tests use Docker's `python` and `postgres` base images, so they pull specific versions.

The sytest tests seem more about verifying that our various topologies work as expected across old and new distros... I suspect focusing on a mix of `oldstable` / `stable` / `testing` is actually semantically closer to what we want there.
