### ISSUE TITLE
`A prev_batch token from incremental sync can be used in the v1 messages API` is flakey

### ISSUE THREAD

**Issue by erikjohnston** [matrix-org/sytest#1026]
see https://buildkite.com/matrix-dot-org/synapse/builds/16739#eef8037b-bff5-46c9-94c5-2a9cc66ce5bb

**Comment by richvdh** [comment]
and https://github.com/matrix-org/synapse/pull/9910/checks?check_run_id=2468789492

**Comment by richvdh** [comment]
and https://github.com/matrix-org/synapse/pull/9450/checks?check_run_id=2794110741

**Comment by clokep** [comment]
and https://github.com/matrix-org/synapse/pull/10385/checks?check_run_id=3058408476

**Comment by richvdh** [comment]
and https://github.com/matrix-org/synapse/pull/10431/checks?check_run_id=3109427234

**Comment by richvdh** [comment]
and https://buildkite.com/matrix-dot-org/sytest/builds/1449#b52bae5b-364b-4fce-a372-149b54eb3fad
