### ISSUE TITLE
`Old leaves are present in gapped incremental syncs` is flakey

### ISSUE THREAD

**Issue by richvdh** [matrix-org/sytest#1037]
see https://buildkite.com/matrix-dot-org/synapse/builds/16951#d131cd2c-199d-4e48-9709-452e63fea61e

**Comment by clokep** [comment]
And https://github.com/matrix-org/synapse/pull/10532/checks?check_run_id=3242345419

**Comment by richvdh** [comment]
And https://github.com/matrix-org/synapse/pull/10520/checks?check_run_id=3236703266

**Comment by richvdh** [comment]
and https://github.com/matrix-org/sytest/issues/1037

**Comment by clokep** [comment]
And https://github.com/matrix-org/synapse/runs/3414626122

**Comment by clokep** [comment]
And https://github.com/matrix-org/synapse/runs/3475978691

**Comment by richvdh** [comment]
And https://github.com/matrix-org/synapse/pull/10784/checks?check_run_id=3547200645

**Comment by richvdh** [comment]
and https://github.com/matrix-org/synapse/pull/10879/checks?check_run_id=3674044100
