### ISSUE TITLE
`Gapped incremental syncs include all state changes` is flaky

### ISSUE THREAD

**Issue by clokep** [matrix-org/sytest#1043]
https://github.com/matrix-org/synapse/pull/9974/checks?check_run_id=2568644902

**Comment by anoadragon453** [comment]
And https://github.com/matrix-org/synapse/pull/10588/checks?check_run_id=3311002021

**Comment by clokep** [comment]
And https://github.com/matrix-org/synapse/runs/3361945259

**Comment by richvdh** [comment]
and https://github.com/matrix-org/synapse/pull/10677/checks?check_run_id=3402736084

**Comment by anoadragon453** [comment]
und https://github.com/matrix-org/synapse/pull/10783/checks?check_run_id=3546892928

**Comment by clokep** [comment]
And https://github.com/matrix-org/synapse/runs/3570688103

**Comment by richvdh** [comment]
And https://github.com/matrix-org/synapse/pull/10873/checks?check_run_id=3674810521
