### ISSUE TITLE
`Can paginate public room list` is flaky

### ISSUE THREAD

**Issue by richvdh** [matrix-org/sytest#1044]
https://github.com/matrix-org/synapse/pull/9981/checks?check_run_id=2582973111

**Comment by richvdh** [comment]
and https://buildkite.com/matrix-dot-org/synapse/builds/17339#650a0408-a6ac-4d1b-8823-b26e43d0a379

**Comment by clokep** [comment]
And https://github.com/matrix-org/synapse/pull/10574/checks?check_run_id=3293529951

**Comment by DMRobertson** [comment]
This showed up twice today.

https://github.com/matrix-org/sytest/runs/4091934326?check_suite_focus=true
https://github.com/matrix-org/sytest/runs/4091934326?check_suite_focus=true

both in #1116. I couldn't see any changes there or in the linked Synapse branch which would explain this.

**Comment by ShadowJonathan** [comment]
Another run in https://github.com/matrix-org/synapse/runs/4447433909?check_suite_focus=true

**Comment by clokep** [comment]
Seen again: https://github.com/matrix-org/synapse/runs/4805751717

**Comment by clokep** [comment]
https://github.com/matrix-org/synapse/runs/5160171515?check_suite_focus=true

**Comment by clokep** [comment]
https://github.com/matrix-org/synapse/runs/5199772896?check_suite_focus=true

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/runs/6076311915?check_suite_focus=true

**Comment by clokep** [comment]
And https://github.com/matrix-org/synapse/runs/6287201691?check_suite_focus=true

**Comment by DMRobertson** [comment]
[Can paginate public room list](https://github.com/matrix-org/synapse/runs/6346842207?check_suite_focus=true)

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/runs/6899135826?check_suite_focus=true

**Comment by richvdh** [comment]
https://github.com/matrix-org/synapse/runs/6932637886?check_suite_focus=true

**Comment by richvdh** [comment]
Pretty sure this is just timing out. It creates 10 rooms, which takes 10 seconds, which is the default test timeout.

See also https://github.com/matrix-org/synapse/issues/6068
