### ISSUE TITLE
`Leaves are present in non-gapped incremental syncs` is flaky

### ISSUE THREAD

**Issue by richvdh** [matrix-org/sytest#1045]
see https://github.com/matrix-org/synapse/runs/2585833072?check_suite_focus=true

**Comment by clokep** [comment]
And https://github.com/matrix-org/synapse/pull/10532/checks?check_run_id=3251172389

**Comment by clokep** [comment]
And https://github.com/matrix-org/synapse/runs/3353652834

**Comment by clokep** [comment]
And https://github.com/matrix-org/synapse/pull/10608/checks?check_run_id=3363512429
