### ISSUE TITLE
DELETE /device/{deviceId} test doesn't send all required parameters

### ISSUE THREAD

**Issue by kroeckx** [matrix-org/sytest#1063]
The tests/10apidoc/12device_management.pl test tries to log in using a password, but doesn't send all the required parameters.

According to the documentation, it should send:
```
{
  "type": "m.login.password",
  "identifier": {
    ...
  },
  "password": "<password>",
  "session": "<session ID>"
}
```

But what it sends is:
```
{"auth":{"user":"@anon-20210704_143726-8:localhost:8800","password":"cashewnuts","type":"m.login.password"}}
```

So it's seems to be missing an identifier and a session, and instead sends a user.

Conduit rightfully sends a 400 Bad Request, at which point Sytest says the test failed.

**Comment by richvdh** [comment]
similar to #1091, though a different test case I think
