### ISSUE TITLE
Presence tests relying on deprecated endpoints

### ISSUE THREAD

**Issue by S7evinK** [matrix-org/sytest#1108]
A list of tests using deprecated endpoints related to presence.
As simply deprecating those sounds like a bad idea, they should be updated to use `/sync` instead. (Or be deprecated and created new ones, whatever is the best solution.)

Using deprecated `GET /r0/events`:

```
tests/30rooms/02members-local.pl:test "Existing members see new members' presence"
tests/30rooms/03members-remote.pl:test "Existing members see new member's presence"
tests/40presence.pl:test "Presence changes are reported to local room members"
tests/40presence.pl:test "Presence changes are also reported to remote room members"
tests/40presence.pl:test "Presence changes to UNAVAILABLE are reported to local room members"
tests/40presence.pl:test "Presence changes to UNAVAILABLE are reported to remote room members"
tests/90jira/SYN-115.pl:multi_test "New federated private chats get full presence information (SYN-115)"
```

Using deprecated `GET /r0/initialSync`:

```
tests/40presence.pl:test "Newly created users see their own presence in /initialSync (SYT-34)"
tests/90jira/SYN-202.pl:multi_test "Left room members do not cause problems for presence"
```

Using deprecated `POST /r0/presence/list/:user_id` (#1101):

```
tests/21presence-events.pl:test "Friends presence changes reports events"
```

**Comment by kegsay** [comment]
Haven't forgotten about this, just been on holiday.

**Comment by richvdh** [comment]
> as they seem to be only related to Synapse. Deprecate, update or blacklist for Dendrite?

can you explain why they don't apply to Synapse?

**Comment by DMRobertson** [comment]
Not sure if related, but I have just seen a test marked SYN-115 fail on synapse develop. Only happens on one of six sytest runs. Flake? https://github.com/matrix-org/synapse/runs/4067253219?check_suite_focus=true

**Comment by richvdh** [comment]
:tada: thanks for sorting this out, @S7evinK !

@DMRobertson I think you're suggesting that #1160 might have introduced flakiness into the SYN-115 test? Entirely plausible, but let's track it elsewhere?
