### ISSUE TITLE
"POST rejects invalid utf-8 in JSON" should also accept M_BAD_JSON

### ISSUE THREAD

**Issue by jfowl** [matrix-org/sytest#1139]
**Describe the bug**

Sytest throws invalid JSON at an endpoint:

```perl
my $reqbody = '{ "username": "a' . chr(0x81) . '" }';
```
and expects the endpoint to return the `M_NOT_JSON`

But this can be parsed as JSON (example with javascript:)
```js
JSON.parse('{"username": "a' + String.fromCharCode(0x81) + '"}');
// returns: { username: "a\u0081" }
```

so imho it is not strictly **not** json, but slightly **bad** json.

Code: https://github.com/matrix-org/sytest/blob/HEAD/tests/10apidoc/01request-encoding.pl#L21

**To Reproduce**

Run sytest against Conduit. See first test here: https://gitlab.com/famedly/conduit/-/pipelines/370760124/test_report

**Expected behavior**

I would suggest that Sytest also accepts `M_BAD_JSON` as a valid error code for this test.

**Reference Conduit issue:** https://gitlab.com/famedly/conduit/-/issues/160#post-rejects-invalid-utf-8-in-json

**Comment by jplatte** [comment]
Does Conduit *ever* return `M_NOT_JSON`? I think serde_json will return a syntax error on non-UTF8, which should certainly be turned into `M_NOT_JSON`.

**Comment by timokoesters** [comment]
Conduit calls ruma's try_from_http_request and returns BAD_JSON if that fails, see ruma_wrapper.rs.

**Comment by jplatte** [comment]
There is many different things that are not "bad JSON" that the error returned from that function can stand for. I'll look into fixing this in Conduit.

**Comment by kroeckx** [comment]
See #1075

**Comment by kroeckx** [comment]
I think this isn't a sytest problem, and this issue should probably get closed.

**Comment by jfowl** [comment]
kk
