### ISSUE TITLE
Docker image is failing to build

### ISSUE THREAD

**Issue by squahtx** [matrix-org/sytest#1176]
Most commits on https://github.com/matrix-org/sytest/commits/develop are failing to build the Docker image
https://github.com/matrix-org/sytest/runs/4460236445?check_suite_focus=true

**Comment by DMRobertson** [comment]
Unless something has changed, I think the underlying cause is #1114

**Comment by squahtx** [comment]
duplicate of #1114

**Comment by sneedboi888** [comment]
try clearing old Docks
