### ISSUE TITLE
Suspected flake: `Inbound federation correctly soft fails events`

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/sytest#1201]
https://github.com/matrix-org/synapse/runs/5392828682?check_suite_focus=true

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/runs/6289786611?check_suite_focus=true

**Comment by DMRobertson** [comment]
https://github.com/matrix-org/synapse/runs/7147431018?check_suite_focus=true

**Comment by richvdh** [comment]
https://github.com/matrix-org/synapse/runs/7677055283?check_suite_focus=true

**Comment by clokep** [comment]
https://github.com/matrix-org/synapse/actions/runs/5124779304/jobs/9217183680?pr=15388

**Comment by clokep** [comment]
I've seen this a lot recently: https://github.com/matrix-org/synapse/actions/runs/6802602432/job/18496098759?pr=16611

**Comment by clokep** [comment]
This is practically a permafail for me now.

**Comment by clokep** [comment]
Hopefully fixed by #1371
