### ISSUE TITLE
Suspected flake: ` Inbound federation redacts events from erased users`

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/sytest#1203]
E.g. https://github.com/matrix-org/synapse/runs/5405867110?check_suite_focus=true

I was able to reproduce this locally with

```shell
docker run --rm -v /home/dmr/workspace/synapse-plain:/src:ro -v /home/dmr/workspace/sytest/:/sytest -v /tmp/logs:/logs -e POSTGRES=1 -e WORKERS=1 -e MULTI_POSTGRES=1 -e SYNAPSE_TEST_LOG_LEVEL=DEBUG matrixdotorg/sytest-synapse:testing --torture-replication 50 -s tests/50federation/32room-getevent.pl
```

**Comment by DMRobertson** [comment]
Couldn't reproduce on Synapse v1.53. Bisecting shows that this was introduced by https://github.com/matrix-org/synapse/commit/dc9fe61050deb5eda59b161e4c0404ff36e3ac59. So maybe this is a Synapse problem rather than a Sytest problem.

**Comment by DMRobertson** [comment]
Sytest's output: [results.txt](https://github.com/matrix-org/sytest/files/8178235/results.txt)

When sytest queries the homeserver under test, it first gets an unredacted copy of the event. It tries again with the same result. Thereafter, the HS under test returns 403 forbidden ("host not in room").

Do we need to have a second user on the HS under test join the room?

**Comment by richvdh** [comment]
the test in question is https://github.com/matrix-org/sytest/blob/develop/tests/50federation/32room-getevent.pl#L44

**Comment by richvdh** [comment]
> Do we need to have a second user on the HS under test join the room?

yes, I think so!
