### ISSUE TITLE
Get rid of non-synced room joins

### ISSUE THREAD

**Issue by S7evinK** [matrix-org/sytest#1247]
As mentioned by @DMRobertson in https://github.com/matrix-org/sytest/pull/1246#pullrequestreview-952250932, it might make sense to remove the non synced version of `matrix_join_room` (and most likely other non synced actions, like `matrix_create_room` etc.)

The reason: Dendrite often flakes due to it's async nature and events might not be persisted yet when hitting `/sync` or other endpoints.

I'm not sure if we can simply replace it or if the non-synced versions have their use cases.

**Comment by richvdh** [comment]
Sounds good - we're not aware of any important usecase for the non-synced versions.

**Comment by S7evinK** [comment]
Solved by #1249
