### ISSUE TITLE
list number of succeeded tests

### ISSUE THREAD

**Issue by NotAFile** [matrix-org/sytest#437]
When making very breaking changes, it is often useful to see if you increased the number of working tests or reduced it

**Comment by anoadragon453** [comment]
Can't use just use the Fail count to infer the same thing?

**Comment by NotAFile** [comment]
No, since tests are skipped if their depencies fail

**Comment by anoadragon453** [comment]
Ah I see. I'm sure we can do that then.

**Comment by NotAFile** [comment]
Awesome, thanks!
