### ISSUE TITLE
Pull out option for whether a test is critical or not

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/sytest#444]
Now that we're starting to test on multiple homeservers (Synapse and Dendrite), tests that are critical failures for Synapse are not for Dendrite during these early stages.

We already have [the ability](https://github.com/matrix-org/sytest/blob/b7af189eacf7e8b4e803aba6cd2e56a64289b270/tests/10apidoc/30room-create.pl#L7) to mark a test as critical or not, however we need to be able to do so in a seperate manner for each homeserver. 

Defining this in a homeserver-specific config file would be cleaner than just a bunch of `if-else`'s in each test case.

**Comment by anoadragon453** [comment]
So for this we'll need a way to refer to each test individually from a separate file. At the moment tests don't really have an ID. They have a file that they're in, and a name describing what they're doing.

Should we use this name as a way to refer to the individual test? Or should we set up some sort of ID like `01register_register_can_create_user` for test "POST /register can create a user" in file `01register.pl`?

**Comment by richvdh** [comment]
https://github.com/matrix-org/sytest/pull/451 attempted this, but as per that PR - I think we decided not to do it.
