### ISSUE TITLE
`bugs` test parameter is outdated and Synapse-specific

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/sytest#636]
Dendrite relies on having a whitelist of tests that it can say it's currently passing. Each time a PR allows more tests to pass, the PR-ee has to add more tests to the testfile. We have a script which will tell the user to do this if a test is passing that we expected to fail.

There's some functionality in Sytest that allows you to put a `bug` parameter into a test, seen in a few places, but notably https://github.com/matrix-org/sytest/blob/0d4ca96bd52d3bd8f1577a61911e98813c7e8b86/tests/61push/07_set_enabled.pl#L60-L63 and https://github.com/matrix-org/sytest/blob/fb631ec58ff46a20482061b278c1032e2575ed1e/tests/41end-to-end-keys/01-upload-key.pl#L38-L41

Dendrite currently passes these tests, but the CI complains that we should be marking them as whitelisted. They are being marked as whitelisted though. While whitelisting should prevent a test from being marked as expected fail, the `bug` parameter still does so. The code for that is here:

https://github.com/matrix-org/sytest/blob/24678f50688dbe922bda0e303fb849f50ec359c3/run-tests.pl#L588

These bugs are specific to Synapse, and should probably be replaced with a `// TODO (Synapse):` instead. Alternatively, we could create a bugs parameter that's specific to each homeserver, but I feel that's a decent chunk of work and ups the barrier of entry of adding support for more homeservers.

**Comment by anoadragon453** [comment]
@richvdh and I have come up with a plan to remove the `bug` parameter and instead replicate the functionality using test blacklists in Synapse.

**Comment by anoadragon453** [comment]
This is fixed by:

https://github.com/matrix-org/synapse/pull/5611
https://github.com/matrix-org/sytest/pull/638

**Comment by Cnly** [comment]
The PR didn't close this issue though...

**Comment by anoadragon453** [comment]
Indeed, oddly.

**Comment by richvdh** [comment]
(it won't be closed until the PR hits the default branch (master))
