### ISSUE TITLE
/rooms/{roomId}/event/{eventId} gives 404 on failure but SyTest expects 403

### ISSUE THREAD

**Issue by Cnly** [matrix-org/sytest#652]
From https://matrix.org/docs/spec/client_server/r0.5.0#get-matrix-client-r0-rooms-roomid-event-eventid:

> Status code 404:
>
> The event was not found or you do not have permission to read this event.

But SyTest:

https://github.com/matrix-org/sytest/blob/19abb6046614bbbeda8dd5153f00a56794c3e2c4/tests/30rooms/51event.pl#L66

and

https://github.com/matrix-org/sytest/blob/19abb6046614bbbeda8dd5153f00a56794c3e2c4/tests/30rooms/51event.pl#L106

**Comment by anoadragon453** [comment]
Fixed by https://github.com/matrix-org/sytest/pull/667 https://github.com/matrix-org/synapse/pull/5798
