### ISSUE TITLE
Sytest should have CI that runs for both Synapse and Dendrite

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/sytest#654]
Just to make sure that when a test is added for Synapse or Dendrite it doesn't break the other homeserver randomly.

**Comment by clokep** [comment]
@anoadragon453 I see at least one build for Dendrite. Is this done now?

**Comment by Kegsay** [comment]
Dendrite soft fails currently so technically doesn't meet the issue description.

**Comment by kegsay** [comment]
It does now.
