### ISSUE TITLE
Possible missing dependency declaration: Test::Identity?

### ISSUE THREAD

**Issue by Cnly** [matrix-org/sytest#850]
When running `./install-deps.pl` on Debian Testing, the script fails at:

```
<omitted>
Running Build test for PEVANS/IO-Async-SSL-0.22.tar.gz
t/00use.t ............... ok   
t/01upgrade.t ........... Can't locate Test/Identity.pm in @INC (you may need to install the Test::Identity module) (@INC contains: <omitted>
<omitted>
Stopping: 'install' failed for 'IO::Async::SSL'.
<omitted>
```

Running `cpan install Test::Identity` (as instructed above) and then `./install-deps.pl` again fixes the problem.

Does `Test::Identity` need to be in `cpanfile`?

**Comment by clokep** [comment]
I don't see any use of `Test::Identity` in SyTest itself, it looks like it might be required by the `IO::Async::SSL` package though? Could it be a bug there?

**Comment by anoadragon453** [comment]
I'm installing a local debian testing box to test.

**Comment by richvdh** [comment]
yes, if anything, that sounds like a bug in `IO::Async::SSL` which should be raised on its bug tracker.

**Comment by anoadragon453** [comment]
Interestingly, I didn't run into this problem on a fresh install of Debian testing. Problems I did run into though that are poorly documented:

* Installing `build-essential` is required on Debian/Ubuntu. Not sure exactly which package though but the error was related to `make`
* Installing postgres build dependencies are required: `sudo apt install libpq-dev`
* `cpan install File:Which` needed to be done manually

**Comment by anoadragon453** [comment]
Yeah, `Test::Identity` was automatically installed for me as part of running `./install-deps.pl`.

**Comment by richvdh** [comment]
sounds like we can close this?
