### ISSUE TITLE
Sytest uses removed POST /rooms/{roomId}/send/{eventType}

### ISSUE THREAD

**Issue by deepbluev7** [matrix-org/sytest#878]
This endpoint was removed [5 years ago](https://github.com/matrix-org/matrix-doc/pull/181) and I'd argue servers shouldn't need support that endpoint just to have unrelated tests succeed.

Conduit ran into this: https://git.koesters.xyz/timo/conduit/issues/35
And it seems like Dendrite did too 3 years ago: https://github.com/matrix-org/dendrite/pull/265

At least the usage to finalize tests should be removed, see here for example: https://github.com/matrix-org/sytest/blob/e14ee8315bd6efbdcda79b0d9412bc5dd8ff61a3/tests/10apidoc/30room-create.pl#L440

The tests for this endpoint should also be made optional imo: https://github.com/matrix-org/sytest/blob/a3396d3766a156debbb287eaa57f58ac4f728d80/tests/10apidoc/34room-messages.pl#L9

**Comment by erikjohnston** [comment]
I think we should just change/delete all the code that uses this endpoint.

**Comment by deepbluev7** [comment]
Well, in some cases it needs to be replaced with the put version, as sending an even is needed in the test, but otherwise I agree.

**Comment by babolivier** [comment]
Reopening as https://github.com/matrix-org/sytest/pull/1084 marked the endpoint as deprecated (which means the tests using it will not run if the `--exclude-deprecated` flag is set, which it isn't by default) but there are still quite a few tests using it.
