### ISSUE TITLE
`Outbound federation will ignore a missing event with bad JSON for room version 6` is flakey

### ISSUE THREAD

**Issue by richvdh** [matrix-org/sytest#885]
https://buildkite.com/matrix-dot-org/synapse/builds/9476#5143875e-134e-465c-b7d0-8e2d5884ae1e

**Comment by clokep** [comment]
Thanks. I'll take a look!

**Comment by clokep** [comment]
I was able to reproduce this by [following the directions to use Redis](https://github.com/matrix-org/sytest/tree/develop/docker#environment-variables) and then running:

```
docker run --network testfoobar --rm -it -e POSTGRES=true -e WORKERS=true -v /Users/clokep/matrix/synapse\:/src:ro -v /Users/clokep/matrix/sytest/logs\:/logs -v /Users/clokep/matrix/sytest\:/sytest:ro matrixdotorg/sytest-synapse:py35 --redis-host testredis --torture-replication 50 tests/50federation/33room-get-missing-events.pl
```

**Comment by clokep** [comment]
I did a bit of debugging of this...after reminding myself what this test does, it seems that the join hasn't fully propagated by the time the additional events are being requested, for some reason the earliest known event is the event before what we think the earliest event is.

**Comment by clokep** [comment]
My break down of what is happening here is that:

1. A room is created on the homeserver
2. Request the "latest" event for the room (which is expected to be a join).
3. Generate an event in the room (the "missing" event).
4. Generate an event in the room (the "sent" event).
5. Two things happen in parallel:
    1. Set up the inbound server to wait for the `get_missing_events` API call.
    2. Send a transaction with the "sent" event to the homeserver.

This all works fine except step 5i. The inbound server expects to receive a `get_missing_events` API call with an `earliest` event being the join from step 2, and the `latest` event being the "sent" event from step 4. It seems that it is receiving the `earliest` as the event *before* the join in step 2.

I think what is happening is that either the federation reader or sender worker does not yet know about the join event from steps 1/2 and we should confirm this before moving on, but I'm not 100% sure how to do that.

**Comment by richvdh** [comment]
yes, I think your analysis is correct. Looking at https://buildkite.com/matrix-dot-org/synapse/builds/9476#5143875e-134e-465c-b7d0-8e2d5884ae1e as an example:

* In [federation_reader.log](https://buildkite.com/organizations/matrix-dot-org/pipelines/synapse/builds/9476/jobs/5143875e-134e-465c-b7d0-8e2d5884ae1e/artifacts/73885734-48fe-47b0-b90f-cec7cbcc77cb), at 15:45:42,912-982 (PUT-341), we see the `send_join` being processed, which dispatches the join event to be persisted (`http://localhost:8828/_synapse/replication/fed_send_events/WTvhEgCSaq).
* In [frontend_proxy.log](https://buildkite.com/organizations/matrix-dot-org/pipelines/synapse/builds/9476/jobs/5143875e-134e-465c-b7d0-8e2d5884ae1e/artifacts/ab2ca753-ef7c-4835-a357-a27dbec11073), at 2020-06-05 15:45:42,928-946, we see that request being processed as POST-4185
* back in federation_reader.log, we then see the sent event arriving at 15:45:42,999 as `PUT-342`, and causing `Requesting missing events between ['$dX_gydvhbt1NhEmETQw3DuJOoTOJIEvCnxj3nAyenJU'] and $tQwVrUKrC7M0bMX6ZxpMTReXmWPMD7d07OmxuuXB-ps`, where `$dX_` is the last of the `createRoom` events, rather than the join event.

Essentially the problem is that, although the event itself has been persisted by the time the `/send_join` request completes, the cache invalidations resulting from it have not yet propagated from the frontend proxy (in its guise as event persister) to the federation reader. (In particular, `get_latest_event_ids_in_room` will be out of date).

I see a few potential solutions:
 * we could have `make_join` wait for the cache invalidations to come back before it returns. There are a couple of other API endpoints (notably, `createRoom`) which do this. However, I'm unconvinced that it's necessary in this case.
 * we make sytest wait for a bit until the cache invalidations have happened. What we normally do in this sort of case is wait for the event in question to come down `/sync`, which serves as an adequate proxy for what we want. (It's only a proxy because the event appearing down `/sync` is neither necessary nor sufficient to prove that the caches on a different worker have been correctly invalidated; but it works ok in practice). In short: poll `/sync` with `$creator` until you see the join event arriving.
 * perhaps we just make sytest tolerate the `earliest` being the earlier event. It's not really a problem: if it happens in production, there will just be a redundant event in the `get_missing_events` response.

option 3 sounds like the least effort to me, but option 2 is valid as well.
