### ISSUE TITLE
Sytest asserts optional fields in /sync

### ISSUE THREAD

**Issue by timokoesters** [matrix-org/sytest#913]
https://github.com/matrix-org/sytest/blob/24bc7c431881042fa5094815b98dff61532480d1/tests/10apidoc/03events-initial.pl#L231

**Comment by timokoesters** [comment]
https://matrix.org/docs/spec/client_server/r0.6.1#get-matrix-client-r0-sync

**Comment by timokoesters** [comment]
So `join`, `invite`, `leave` but also `rooms` and maybe some others

**Comment by timokoesters** [comment]
Implemented on our fork: https://github.com/valkum/sytest/pull/224/files

**Comment by clokep** [comment]
Any chance you'd be willing to PR changes back to make sytest more spec compliant?
