### ISSUE TITLE
Question concerning tests with EXPECTED FAIL.

### ISSUE THREAD

**Issue by Jbbouille** [matrix-org/sytest#946]
I am sorry for this dummy question but I dont understand what `EXPECTED FAIL` means. 

After executing the tests on `conduit` project I got this line:
`    Test 4 POST /register returns the same device_id as that in the request... EXPECTED FAIL`

Does it means that it should fails and it don't so I must investigate this test, or that it has failed as expected ? 

I think that it means that my test should fails and it don't, but I can't find in the [code](https://github.com/matrix-org/sytest/blob/develop/tests/10apidoc/01register.pl#L109) a trace of a 'fail' verification.

I hope my question is clear.

**Comment by clokep** [comment]
An EXPECTED FAIL test is a test that fails and is expected to fail.

For synapse I believe the list of tests to treat this way is at https://github.com/matrix-org/synapse/blob/develop/sytest-blacklist

I don't know what would be getting used for conduit? I assume it is a flag that can be passed in.
