### ISSUE TITLE
`Newly left rooms appear in the leave section of gapped sync` seems flakey

### ISSUE THREAD

**Issue by reivilibre** [matrix-org/sytest#948]
See: https://buildkite.com/matrix-dot-org/synapse/builds/11617#cc8de19d-1b10-4ad1-bc11-9f421147624e

Happened twice in a row. Seems like the test is timing out?

**Comment by richvdh** [comment]
seems to have been introduced by https://github.com/matrix-org/synapse/pull/8170

**Comment by erikjohnston** [comment]
This seems to be fixed?
