### ISSUE TITLE
"After changing password, can log in with new password" tries to login with an access_token

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/sytest#954]
https://github.com/matrix-org/sytest/blob/c0c8009b2a736694823a1a92dadccaa41f61e638/tests/14account/01change-password.pl#L54-L72 

I don't think it should be trying to do that :(

Logs can be found on https://buildkite.com/matrix-dot-org/synapse/builds/11896#

**Comment by erikjohnston** [comment]
The access token will get auto added by `do_request_json_for`. You should be able to change it to `$user->http->do_request_json( ... )`
