### ISSUE TITLE
Best way to work on both Dendrite and Synapse at the same time (multiple instances)?

### ISSUE THREAD

**Issue by MadLittleMods** [matrix-org/sytest#997]
What's the recommended/best way to work on both Dendrite and Synapse and run Sytest at the same time?

Currently, you need to create `server-0`, `server-1` configs and a bunch of files get generated when running against either. I don't want to write my configs over and over. Can I specify `server-x`?

On https://github.com/matrix-org/dendrite/blob/master/docs/sytest.md#using-the-sytest-docker-image, they recommend using the Docker image of Sytest but I want to run against the Sytest source because I had to add some necessary `log_if_fail` information to Sytest itself when I was debugging.

## Possible workarounds

One option is just to have multiple clones of the Sytest repo.

**Comment by clokep** [comment]
I think you can mount the proper source directories, the command I use is:

```sh
docker run --rm -it -v /Users/clokep/matrix/synapse\:/src:ro -v /Users/clokep/matrix/sytest/logs\:/logs -v /Users/clokep/matrix/sytest\:/sytest:ro matrixdotorg/sytest-synapse:py35
```

**Comment by MadLittleMods** [comment]
@clokep Ouu, I missed that you could share your local Sytest source in the Docker image :+1:

Is there a good way to solve the problem of the `server-x` configs in the Sytest source needing to be different for Dendrite and Synapse?

**Comment by clokep** [comment]
> Is there a good way to solve the problem of the `server-x` configs in the Sytest source needing to be different for Dendrite and Synapse?

I'm not sure what those are so I'm not sure. Are they auto-generated during a run?

**Comment by MadLittleMods** [comment]
hmmm, thinking about it more, might not be necessary. The `server-x` stuff was only for the [manual setup](https://github.com/matrix-org/dendrite/blob/master/docs/sytest.md#manually-setting-up-sytest) and the Docker container is new every time.


I was able to get Docker working for both via these commands. Thanks for the nudge to go this direction!

```
docker run --rm --name sytest-dendrite -v "/Users/eric/Documents/github/sytest:/sytest" \
  -v "/Users/eric/Documents/github/dendrite:/src" \
  -v "/Users/eric/logs:/logs" \
  -v "/Users/eric/go:/gopath" -e "POSTGRES=1" -e "DENDRITE_TRACE_HTTP=1" \
  matrixdotorg/sytest-dendrite:latest tests/31sync/09archived.pl
```

```
docker run --rm --name sytest -v "/Users/eric/Documents/github/sytest:/sytest" \
  -v "/Users/eric/Documents/github/synapse:/src" \
  -v "/Users/eric/logs:/logs" \
  -v "/Users/eric/go:/gopath" -e "POSTGRES=1" \
  matrixdotorg/sytest-synapse:py37 tests/31sync/09archived.pl
```
